version: "3.6"

services:
  database:
    image: postgres:12
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=go-boilerplate-dev
      - POSTGRES_PASSWORD=postgres
  api:
    image: go-docker-api-boilerplate:latest
    ports:
      - 4000:4000
    volumes:
      - ./:/app
    links:
      - database
    environment:
      - PORT=4000
      - DOCS=true
      - CORS=false
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go-boilerplate-dev

volumes:
  psql: {}
